CREATE DATABASE employees_Database;
CREATE TABLE employees_Table (
id INT AUTO_INCREMENT PRIMARY KEY,
last_Name VARCHAR (50) NOT NULL,
first_Name VARCHAR (50) NOT NULL,
middle_Name VARCHAR (50),
age INT NOT NULL,
job_Type VARCHAR (100),
current_Status VARCHAR (100) NOT NULL DEFAULT 'Unemployed'
);
INSERT INTO employees_Table (last_Name, first_Name, middle_Name, age, job_Type, current_Status) VALUES
('García', 'Sofía', 'Alejandra', 28, 'Software Engineer', 'Active'),
('Smith', 'John', 'Michael', 45, 'Project Manager', 'Active'),
('López', 'Carlos', NULL, 34, 'Data Analyst', 'Active'),
('Chen', 'Mei', 'Lin', 52, 'Financial Advisor', 'Active'),
('Rodríguez', 'Luis', 'Alberto', 22, 'Marketing Specialist', 'Active'),
('Williams', 'Sarah', 'Elizabeth', 30, 'HR Coordinator', 'Active'),
('Fernández', 'Ana', 'María', 41, 'Operations Director', 'Active'),
('Brown', 'David', 'James', 58, 'System Administrator', 'Active'),
('Martínez', 'Elena', NULL, 25, 'Graphic Designer', 'Active'),
('Miller', 'Robert', 'Alan', 37, 'Sales Representative', 'Active'),
('Sánchez', 'Javier', 'Ignacio', 49, 'Chief Executive Officer', 'Active'),
('Davis', 'Jessica', 'Nicole', 31, 'Research Scientist', 'Active'),
('Pérez', 'Ricardo', 'Manuel', 60, NULL, 'Unemployed'),
('Jones', 'Emily', NULL, 29, 'Content Writer', 'Active'),
('González', 'Miguel', 'Ángel', 33, 'Network Engineer', 'Active'),
('Wilson', 'Olivia', 'Grace', 40, 'Product Designer', 'Active'),
('Ruiz', 'Daniela', 'Paz', 23, 'Front-End Developer', 'Active'),
('Moore', 'Thomas', 'Edward', 55, 'Supply Chain Manager', 'Active'),
('Hernández', 'Andrés', NULL, 36, 'Recruiter', 'Active'),
('Taylor', 'Chloe', 'Rose', 27, 'Social Media Manager', 'Active'),
('Díaz', 'Valeria', 'Isabel', 48, 'Executive Assistant', 'Active'),
('Anderson', 'Ryan', 'Patrick', 32, 'Business Analyst', 'Active'),
('Vázquez', 'Jorge', 'Antonio', 51, 'Teacher', 'Active'),
('Thomas', 'Megan', NULL, 24, 'Customer Support Agent', 'Active'),
('Gómez', 'Laura', 'Beatriz', 39, 'Paralegal', 'Active'),
('Jackson', 'Kevin', 'Lee', 43, 'Plumber', 'Active'),
('Moreno', 'Paula', 'Victoria', 26, 'Architect', 'Active'),
('White', 'Noah', 'Benjamin', 50, 'Electrician', 'Active'),
('Jiménez', 'Felipe', 'Santiago', 35, 'Chef', 'Active'),
('Harris', 'Mia', 'Jade', 21, 'Veterinary Technician', 'Active'),
('Alonso', 'Diego', NULL, 53, 'Pilot', 'Active'),
('Martin', 'Lucas', 'Andrew', 46, 'Construction Worker', 'Active'),
('Navarro', 'Gabriela', 'Luz', 38, 'Nurse', 'Active'),
('Thompson', 'Jack', 'Henry', 44, 'Firefighter', 'Active'),
('Castro', 'Héctor', 'Raúl', 57, NULL, 'Unemployed'),
('Garcia', 'Isabella', 'Andrea', 20, 'Librarian', 'Active'),
('Clark', 'Samuel', 'Joseph', 59, 'Geologist', 'Active'),
('Herrera', 'Marta', 'Teresa', 42, 'Pharmacist', 'Active'),
('Lewis', 'Jacob', NULL, 31, 'Dentist', 'Active'),
('Flores', 'Esteban', 'Darío', 54, 'Surgeon', 'Active'),
('Robinson', 'Ella', 'Faith', 29, 'Psychologist', 'Active'),
('Morales', 'Guillermo', 'Julián', 30, 'Journalist', 'Active'),
('Walker', 'Alexander', 'Dean', 47, 'Economist', 'Active'),
('Rojas', 'Natalia', 'Soledad', 28, 'Urban Planner', 'Active'),
('Hall', 'Grace', 'Harper', 56, 'Real Estate Agent', 'Active'),
('Vidal', 'Sebastián', NULL, 33, 'Mechanic', 'Active'),
('Allen', 'Zoe', 'Violet', 27, 'Fitness Trainer', 'Active'),
('Aguilar', 'Ramón', 'Jesús', 45, 'Photographer', 'Active'),
('Young', 'Penelope', 'Kate', 36, 'Travel Agent', 'Active'),
('Cruz', 'Marcos', 'Elías', 52, 'Web Developer', 'Active'),
('Baker', 'Lily', 'Rose', 25, 'Copywriter', 'Active'),
('Delgado', 'Oscar', NULL, 40, 'Biologist', 'Active'),
('King', 'Benjamin', 'Leo', 34, 'Chemist', 'Active'),
('Soto', 'Andrea', 'Lucía', 22, 'Electrician', 'Active'),
('Carter', 'Elijah', 'Cole', 41, 'Civil Engineer', 'Active'),
('Ortiz', 'Pilar', 'Carmen', 58, 'Professor', 'Active'),
('Mitchell', 'Henry', 'Arthur', 39, 'Statistician', 'Active'),
('Blanco', 'Eva', 'Inés', 35, 'Oceanographer', 'Active'),
('Patterson', 'Sofia', 'Joy', 24, 'Meteorologist', 'Active'),
('Rivera', 'Juan', 'Carlos', 53, NULL, 'Unemployed'),
('Scott', 'Hannah', 'Lynn', 38, 'Lobbyist', 'Active'),
('Méndez', 'Mario', 'Gabriel', 48, 'Auditor', 'Active'),
('Ramírez', 'Julia', 'Esther', 26, 'Interior Designer', 'Active'),
('Hughes', 'Wyatt', 'Finn', 37, 'Investment Banker', 'Active'),
('Herrera', 'Clara', 'Elena', 50, 'Social Worker', 'Active'),
('Foster', 'Caleb', 'Ethan', 32, 'Librarian', 'Active'),
('Guerrero', 'Laura', 'Sofía', 29, 'Speech Pathologist', 'Active'),
('Barnes', 'Dylan', 'Michael', 43, 'Truck Driver', 'Active'),
('Cabrera', 'Emilio', 'José', 55, 'High School Teacher', 'Active'),
('Fisher', 'Avery', 'Noelle', 21, 'Fitness Trainer', 'Active'),
('Reyes', 'Alejandro', 'David', 46, 'Pilot', 'Active'),
('Morgan', 'Victoria', 'Skye', 30, 'Executive Chef', 'Active'),
('Molina', 'Jesús', NULL, 51, 'Veterinarian', 'Active'),
('Ross', 'Stella', 'Marie', 23, 'Barista', 'Active'),
('Silva', 'Lucía', 'Fernanda', 49, 'Mechanical Engineer', 'Active'),
('Ward', 'Adrian', 'Leo', 34, 'Police Officer', 'Active'),
('Vega', 'Elena', 'Cristina', 44, 'Flight Attendant', 'Active'),
('Cooper', 'Owen', 'Rhys', 57, 'Journalist', 'Active'),
('Crespo', 'Mateo', 'Pablo', 28, 'Electrician', 'Active'),
('Richardson', 'Brooke', 'Olivia', 33, 'Financial Analyst', 'Active'),
('Peralta', 'Carmen', 'Rosa', 59, 'Physiotherapist', 'Active'),
('Gray', 'Nolan', 'Pierce', 27, 'Geologist', 'Active'),
('Mendoza', 'Diego', 'Raúl', 31, 'Paramedic', 'Active'),
('James', 'Riley', 'Quinn', 40, 'IT Consultant', 'Active'),
('Acosta', 'Beatriz', 'Luisa', 54, 'Marketing Director', 'Active'),
('Price', 'Gabriel', 'Elias', 26, 'Museum Curator', 'Active'),
('Salazar', 'Inés', 'Rocío', 42, 'Chiropractor', 'Active'),
('Bailey', 'Derek', 'Scott', 45, 'Dentist', 'Active'),
('Torres', 'Rafael', 'Ernesto', 38, 'Professor', 'Active'),
('Sanders', 'Hazel', 'Willow', 20, 'Receptionist', 'Active'),
('Castro', 'Sara', 'Jimena', 56, 'Forensic Scientist', 'Active'),
('Bryant', 'Marcus', 'Drew', 35, 'Data Scientist', 'Active'),
('Duque', 'Fabiola', 'Esperanza', 36, 'Accountant', 'Active'),
('Powell', 'Jude', 'Liam', 47, 'Aerospace Engineer', 'Active'),
('Montes', 'Claudia', NULL, 52, NULL, 'Unemployed'),
('Flores', 'Roberto', 'Carlos', 25, 'Photographer', 'Active'),
('Jenkins', 'Kimberly', 'Sue', 41, 'Operations Manager', 'Active'),
('Ramos', 'Mario', 'Andrés', 22, 'Chef', 'Active'),
('Perry', 'Dean', 'Martin', 39, 'Librarian', 'Active'),
('Vargas', 'Teresa', 'Angélica', 33, 'HR Manager', 'Active'),
('Russell', 'Jordan', 'Lee', 58, 'Biotech Specialist', 'Active'),
('Bravo', 'Hugo', 'Javier', 27, 'Graphic Designer', 'Active'),
('Wood', 'Michelle', 'Ann', 44, 'Electrician', 'Active'),
('Serrano', 'Ricardo', 'Jesús', 30, 'Teacher', 'Active'),
('Butler', 'Mason', 'Kyle', 53, 'Physicist', 'Active'),
('Ibarra', 'Diana', 'Carolina', 29, 'Real Estate Agent', 'Active'),
('Hayes', 'Logan', 'Samuel', 46, 'Firefighter', 'Active'),
('Luna', 'Sofía', 'Alejandra', 37, 'Software Developer', 'Active'),
('Bennett', 'Stella', 'Rose', 50, 'Social Worker', 'Active'),
('Cano', 'Pedro', 'Pablo', 23, 'Nurse', 'Active'),
('Foster', 'Aubrey', 'Claire', 48, 'Project Manager', 'Active'),
('Peña', 'Elena', 'Victoria', 34, 'Marketing Specialist', 'Active'),
('Barnes', 'Elijah', 'Jacob', 55, 'Accountant', 'Active'),
('Del Río', 'Marcela', 'Inés', 28, 'Recruiter', 'Active'),
('Cole', 'Wesley', 'Owen', 49, 'Supply Chain Analyst', 'Active'),
('Rivas', 'Antonio', 'Miguel', 36, 'Customer Service Manager', 'Active'),
('Henderson', 'Julia', 'Grace', 51, NULL, 'Unemployed'),
('Molina', 'David', 'Fernando', 24, 'Lawyer', 'Active'),
('Kelly', 'Lauren', 'Ashley', 40, 'Architect', 'Active'),
('Pizarro', 'Jorge', 'Daniel', 31, 'Financial Advisor', 'Active'),
('Stone', 'Leo', 'Max', 57, 'Civil Engineer', 'Active'),
('Silva', 'Carla', 'Patricia', 32, 'Journalist', 'Active'),
('Brooks', 'Isaac', 'Alexander', 54, 'Statistician', 'Active'),
('Velez', 'Renata', 'Camila', 26, 'Chef', 'Active'),
('Wallace', 'Henry', 'James', 42, 'Dentist', 'Active'),
('Zárate', 'Gabriela', 'Luz', 38, 'Urban Planner', 'Active'),
('Peterson', 'Luke', 'Ryan', 43, 'Meteorologist', 'Active'),
('Núñez', 'Sergio', 'Andrés', 56, 'Pharmacist', 'Active'),
('Grant', 'Violet', 'Rose', 25, 'Content Writer', 'Active'),
('Rojas', 'Javier', 'Ignacio', 41, 'High School Teacher', 'Active'),
('Murray', 'Mia', 'Isabelle', 22, 'Travel Agent', 'Active'),
('Quiroga', 'Felipe', 'Santiago', 47, 'Mechanic', 'Active'),
('Long', 'Ava', 'Elizabeth', 30, 'Biologist', 'Active'),
('Vidal', 'Esteban', 'José', 59, 'Lobbyist', 'Active'),
('Harrison', 'Oscar', 'Dean', 33, 'Surgeon', 'Active'),
('Tapia', 'Camila', 'Andrea', 27, 'Psychologist', 'Active'),
('Gibson', 'Nora', 'Jean', 50, 'Economist', 'Active'),
('Fuentes', 'Manuel', 'Ricardo', 35, NULL, 'Unemployed'),
('Ellis', 'Owen', 'Scott', 45, 'System Administrator', 'Active'),
('Guerrero', 'Lucía', 'María', 34, 'Graphic Designer', 'Active'),
('Graham', 'Caleb', 'Liam', 52, 'Sales Representative', 'Active'),
('Paredes', 'Sofía', 'Isabel', 29, 'Data Analyst', 'Active'),
('Reid', 'Ethan', 'Oliver', 44, 'Operations Director', 'Active'),
('Soto', 'Jorge', 'Antonio', 31, 'HR Coordinator', 'Active'),
('Chapman', 'Hannah', 'Grace', 58, 'Financial Advisor', 'Active'),
('Salinas', 'Diego', 'Alejandro', 26, 'Software Engineer', 'Active'),
('Kennedy', 'Chloe', 'Nicole', 46, 'Project Manager', 'Active'),
('Ochoa', 'Ricardo', 'Daniel', 39, 'Marketing Specialist', 'Active'),
('Shaw', 'Leo', 'Benjamin', 55, 'Network Engineer', 'Active'),
('Peña', 'Valeria', 'Camila', 20, NULL, 'Unemployed'),
('Wallace', 'Liam', 'Patrick', 42, 'Product Designer', 'Active'),
('Méndez', 'Andrea', 'Lucía', 37, 'Front-End Developer', 'Active'),
('Curtis', 'Noah', 'Thomas', 53, 'Supply Chain Manager', 'Active'),
('Bravo', 'Laura', 'Beatriz', 28, 'Recruiter', 'Active'),
('Fleming', 'Ryan', 'James', 41, 'Social Media Manager', 'Active'),
('Silva', 'Javier', 'Ignacio', 36, 'Executive Assistant', 'Active'),
('Weber', 'Mia', 'Jade', 57, 'Business Analyst', 'Active'),
('Aguirre', 'Pablo', 'Andrés', 21, 'Teacher', 'Active'),
('West', 'Olivia', 'Grace', 40, 'Customer Support Agent', 'Active');
INSERT INTO employees_Table (last_Name, first_Name, middle_Name, age, job_Type, current_Status) VALUES
('Medina', 'Jesús', 'Manuel', 35, 'Paralegal', 'Active'),
('Cole', 'Jessica', 'Lynn', 49, 'Plumber', 'Active'),
('Castro', 'Fabián', 'Ernesto', 23, 'Architect', 'Active'),
('Howard', 'Cameron', 'Scott', 52, 'Electrician', 'Active'),
('Arias', 'Sofía', 'Paz', 32, 'Chef', 'Active'),
('Gray', 'Elias', 'Owen', 44, 'Veterinary Technician', 'Active'),
('Sosa', 'Daniela', 'Victoria', 27, 'Pilot', 'Active'),
('Ford', 'Ethan', 'Henry', 50, 'Construction Worker', 'Active'),
('Vargas', 'Miguel', 'Ángel', 38, 'Nurse', 'Active'),
('Gonzales', 'Chloe', 'Mae', 46, 'Firefighter', 'Active'),
('Ríos', 'Laura', 'Isabel', 55, NULL, 'Unemployed'),
('Kelly', 'Brandon', 'Kyle', 20, 'Librarian', 'Active'),
('Dixon', 'Harper', 'Grace', 58, 'Geologist', 'Active'),
('Méndez', 'Andrés', 'Felipe', 41, 'Pharmacist', 'Active'),
('Sandoval', 'Lucía', 'Fernanda', 29, 'Dentist', 'Active'),
('Peters', 'Jacob', 'Allen', 30, 'Surgeon', 'Active'),
('Luna', 'Ricardo', 'David', 47, 'Psychologist', 'Active'),
('Hayes', 'Emily', 'Rose', 28, 'Journalist', 'Active'),
('Herrera', 'Juan', 'Carlos', 56, 'Economist', 'Active'),
('Warren', 'Zoe', 'Michelle', 33, 'Urban Planner', 'Active'),
('Vargas', 'Felipe', 'Andrés', 25, 'Real Estate Agent', 'Active'),
('Flores', 'Gabriela', 'María', 51, 'Mechanic', 'Active'),
('Nash', 'Ryan', 'Patrick', 36, 'Fitness Trainer', 'Active'),
('Morales', 'Javier', 'Ignacio', 45, 'Photographer', 'Active'),
('Powell', 'Mia', 'Sofia', 22, 'Travel Agent', 'Active'),
('Silva', 'Óscar', 'René', 40, 'Web Developer', 'Active'),
('Peréz', 'Valeria', 'Isabel', 53, 'Copywriter', 'Active'),
('Cruz', 'Sebastián', 'Andrés', 34, 'Biologist', 'Active'),
('Brooks', 'Allison', 'Claire', 42, 'Chemist', 'Active'),
('Guzmán', 'Santiago', 'Elías', 57, 'Electrician', 'Active'),
('Shaw', 'Madison', 'Lynn', 31, 'Civil Engineer', 'Active'),
('Rojas', 'Héctor', 'Manuel', 48, 'Professor', 'Active'),
('West', 'Natalie', 'Joy', 24, 'Statistician', 'Active'),
('Acuña', 'Esteban', 'Darío', 39, 'Oceanographer', 'Active'),
('Fisher', 'Aubrey', 'Rose', 54, 'Meteorologist', 'Active'),
('Ramírez', 'Daniela', 'Paz', 26, NULL, 'Unemployed'),
('Kennedy', 'Owen', 'Rhys', 43, 'Lobbyist', 'Active'),
('Ochoa', 'Lucía', 'Elena', 37, 'Auditor', 'Active'),
('Cole', 'Thomas', 'James', 59, 'Interior Designer', 'Active'),
('Scott', 'Penelope', 'Jane', 27, 'Investment Banker', 'Active'),
('López', 'Miguel', 'Ángel', 50, 'Social Worker', 'Active'),
('Harris', 'Skylar', 'Dean', 32, 'Librarian', 'Active'),
('Molina', 'Ana', 'Carolina', 44, 'Speech Pathologist', 'Active'),
('Perry', 'Ethan', 'Cole', 55, 'Truck Driver', 'Active'),
('Rivera', 'Mariana', 'Sofía', 21, 'High School Teacher', 'Active'),
('Morgan', 'Andrew', 'Thomas', 46, 'Fitness Trainer', 'Active'),
('Soto', 'Julia', 'Grace', 30, 'Pilot', 'Active'),
('Barnes', 'Leo', 'Alexander', 51, 'Executive Chef', 'Active'),
('Vidal', 'Andrea', 'Paula', 23, 'Veterinarian', 'Active'),
('Foster', 'Henry', 'Arthur', 49, 'Barista', 'Active'),
('Wallace', 'Carmen', 'Rosa', 34, 'Mechanical Engineer', 'Active'),
('Reyes', 'Luis', 'Alberto', 57, 'Police Officer', 'Active'),
('Díaz', 'Valeria', 'Cristina', 28, 'Flight Attendant', 'Active'),
('Cooper', 'Elijah', 'Wyatt', 45, 'Journalist', 'Active'),
('Acosta', 'Sebastián', 'Pablo', 33, 'Electrician', 'Active'),
('Richardson', 'Brooke', 'Marie', 52, 'Financial Analyst', 'Active'),
('Peralta', 'Jorge', 'Antonio', 25, 'Physiotherapist', 'Active'),
('Gray', 'Nora', 'Elizabeth', 40, 'Geologist', 'Active'),
('Mendoza', 'David', 'Alan', 53, 'Paramedic', 'Active'),
('James', 'Chloe', 'Lynn', 29, 'IT Consultant', 'Active'),
('Alonso', 'Ricardo', 'Manuel', 41, 'Marketing Director', 'Active'),
('Price', 'Ella', 'Faith', 58, 'Museum Curator', 'Active'),
('Salazar', 'Mario', 'Gabriel', 36, 'Chiropractor', 'Active'),
('Bailey', 'Victoria', 'Skye', 47, 'Dentist', 'Active'),
('Torres', 'Javier', 'Ernesto', 22, 'Professor', 'Active'),
('Sanders', 'Lucas', 'Finn', 55, 'Receptionist', 'Active'),
('Castro', 'Jimena', 'Andrea', 37, 'Forensic Scientist', 'Active'),
('Bryant', 'Noah', 'Daniel', 44, 'Data Scientist', 'Active'),
('Duque', 'Esteban', 'Jesús', 35, 'Accountant', 'Active'),
('Powell', 'Ava', 'Grace', 50, 'Aerospace Engineer', 'Active'),
('Montes', 'Héctor', 'Raúl', 26, 'Chef', 'Active'),
('Flores', 'Julia', 'Beatriz', 42, 'Operations Manager', 'Active'),
('Jenkins', 'Robert', 'Alan', 33, 'Chef', 'Active'),
('Ramos', 'Isabella', 'Andrea', 56, 'Librarian', 'Active'),
('Perry', 'Charles', 'Edward', 28, 'HR Manager', 'Active'),
('Vargas', 'Daniela', 'Luz', 49, 'Biotech Specialist', 'Active'),
('Russell', 'Oliver', 'Dean', 31, 'Graphic Designer', 'Active'),
('Bravo', 'Sofía', 'Alejandra', 53, 'Electrician', 'Active'),
('Wood', 'Gabriel', 'Michael', 24, 'Teacher', 'Active'),
('Serrano', 'Laura', 'María', 40, 'Physicist', 'Active'),
('Butler', 'Ethan', 'Scott', 57, 'Real Estate Agent', 'Active'),
('Ibarra', 'Mario', 'David', 30, 'Firefighter', 'Active'),
('Hayes', 'Chloe', 'Rose', 46, 'Software Developer', 'Active'),
('Luna', 'Ricardo', 'José', 39, 'Social Worker', 'Active'),
('Bennett', 'Ryan', 'Patrick', 51, 'Nurse', 'Active'),
('Cano', 'Elena', 'Victoria', 27, 'Project Manager', 'Active'),
('Foster', 'Thomas', 'Edward', 43, 'Marketing Specialist', 'Active'),
('Peña', 'Andrés', 'Felipe', 54, 'Accountant', 'Active'),
('Barnes', 'Grace', 'Harper', 25, 'Recruiter', 'Active'),
('Del Río', 'Javier', 'Ignacio', 48, 'Supply Chain Analyst', 'Active'),
('Cole', 'Mia', 'Jade', 34, 'Customer Service Manager', 'Active'),
('Rivas', 'Antonio', 'José', 55, NULL, 'Unemployed'),
('Henderson', 'Lucas', 'Andrew', 29, 'Lawyer', 'Active'),
('Kelly', 'Ava', 'Elizabeth', 42, 'Architect', 'Active'),
('Pizarro', 'Sofía', 'Isabel', 36, 'Financial Advisor', 'Active'),
('Stone', 'Benjamin', 'Leo', 50, 'Civil Engineer', 'Active'),
('Silva', 'David', 'James', 33, 'Journalist', 'Active'),
('Brooks', 'Penelope', 'Kate', 57, 'Statistician', 'Active'),
('Velez', 'Juan', 'Carlos', 21, 'Chef', 'Active'),
('Wallace', 'Ella', 'Rose', 45, 'Dentist', 'Active'),
('Zárate', 'Marcos', 'Elías', 38, 'Urban Planner', 'Active'),
('Peterson', 'Hannah', 'Lynn', 52, 'Meteorologist', 'Active'),
('Núñez', 'Pablo', 'Antonio', 26, 'Pharmacist', 'Active'),
('Grant', 'Ethan', 'Oliver', 41, 'Content Writer', 'Active'),
('Rojas', 'Javier', 'Andrés', 58, 'High School Teacher', 'Active'),
('Murray', 'Valeria', 'Paz', 30, 'Travel Agent', 'Active'),
('Quiroga', 'Luis', 'Alberto', 53, 'Mechanic', 'Active'),
('Long', 'Chloe', 'Nicole', 24, 'Biologist', 'Active'),
('Vidal', 'Ricardo', 'Manuel', 40, 'Lobbyist', 'Active'),
('Harrison', 'Aurora', 'Dawn', 59, 'Surgeon', 'Active'),
('Tapia', 'Miguel', 'Ángel', 35, 'Psychologist', 'Active'),
('Gibson', 'Mia', 'Sofia', 56, 'Economist', 'Active'),
('Fuentes', 'Laura', 'Beatriz', 22, 'System Administrator', 'Active'),
('Ellis', 'Owen', 'Rhys', 43, 'Graphic Designer', 'Active'),
('Guerrero', 'Diego', 'Alejandro', 37, 'Sales Representative', 'Active'),
('Graham', 'Isabella', 'Andrea', 54, 'Data Analyst', 'Active'),
('Paredes', 'Daniel', 'Felipe', 29, 'Operations Director', 'Active'),
('Reid', 'Ava', 'Claire', 47, 'HR Coordinator', 'Active'),
('Soto', 'Lucía', 'Fernanda', 32, 'Financial Advisor', 'Active'),
('Chapman', 'Ryan', 'Patrick', 51, 'Software Engineer', 'Active'),
('Salinas', 'Elena', 'Cristina', 26, 'Project Manager', 'Active'),
('Kennedy', 'Thomas', 'Edward', 44, 'Marketing Specialist', 'Active'),
('Ochoa', 'Sofía', 'Julieta', 31, 'Network Engineer', 'Active'),
('Shaw', 'Adrian', 'Leo', 58, 'Product Designer', 'Active'),
('Peña', 'Marcos', 'Elías', 20, 'Front-End Developer', 'Active');
INSERT INTO employees_Table (last_Name, first_Name, middle_Name, age, job_Type, current_Status) VALUES
('Wallace', 'Julia', 'Nicole', 42, 'Supply Chain Manager', 'Active'),
('Méndez', 'David', 'James', 37, 'Recruiter', 'Active'),
('Curtis', 'Olivia', 'Grace', 53, 'Social Media Manager', 'Active'),
('Bravo', 'Kevin', 'Lee', 28, 'Executive Assistant', 'Active'),
('Fleming', 'Jessica', 'Lynn', 41, 'Business Analyst', 'Active'),
('Silva', 'Robert', 'Alan', 36, 'Teacher', 'Active'),
('Weber', 'Emily', 'Sarah', 57, 'Customer Support Agent', 'Active'),
('Aguirre', 'John', 'Michael', 21, 'Paralegal', 'Active'),
('West', 'Laura', 'Beatriz', 40, 'Plumber', 'Active'),
('Medina', 'Mario', 'Gabriel', 35, 'Architect', 'Active'),
('Cole', 'Valeria', 'Isabel', 49, 'Electrician', 'Active'),
('Castro', 'Ricardo', 'Manuel', 23, 'Chef', 'Active'),
('Howard', 'Ana', 'María', 52, 'Veterinary Technician', 'Active'),
('Arias', 'Gabriel', 'Elias', 32, 'Pilot', 'Active'),
('Gray', 'Sofía', 'Alejandra', 44, 'Construction Worker', 'Active'),
('Sosa', 'Daniel', 'Felipe', 27, 'Nurse', 'Active'),
('Ford', 'Mia', 'Jade', 50, 'Firefighter', 'Active'),
('Vargas', 'Lucas', 'Andrew', 38, NULL, 'Unemployed'),
('Gonzales', 'Isabella', 'Andrea', 46, 'Librarian', 'Active'),
('Ríos', 'Thomas', 'Edward', 55, 'Geologist', 'Active'),
('Kelly', 'Chloe', 'Rose', 20, 'Pharmacist', 'Active'),
('Dixon', 'Owen', 'Rhys', 58, 'Dentist', 'Active'),
('Méndez', 'Ryan', 'Patrick', 41, 'Surgeon', 'Active'),
('Sandoval', 'Hannah', 'Lynn', 29, 'Psychologist', 'Active'),
('Peters', 'Ethan', 'Oliver', 30, 'Journalist', 'Active'),
('Luna', 'Victoria', 'Skye', 47, 'Economist', 'Active'),
('Hayes', 'David', 'James', 28, 'Urban Planner', 'Active'),
('Herrera', 'Avery', 'Noelle', 56, 'Real Estate Agent', 'Active'),
('Warren', 'Julian', 'Dean', 33, 'Mechanic', 'Active'),
('Vargas', 'Ella', 'Faith', 25, 'Fitness Trainer', 'Active'),
('Flores', 'Alexander', 'Cole', 51, 'Photographer', 'Active'),
('Nash', 'Penelope', 'Kate', 36, 'Travel Agent', 'Active'),
('Morales', 'Samuel', 'Joseph', 45, 'Web Developer', 'Active'),
('Powell', 'Grace', 'Harper', 22, 'Copywriter', 'Active'),
('Silva', 'Elijah', 'Kyle', 40, 'Biologist', 'Active'),
('Peréz', 'Zoey', 'Violet', 53, 'Chemist', 'Active'),
('Cruz', 'Leo', 'Benjamin', 34, 'Electrician', 'Active'),
('Brooks', 'Lily', 'Rose', 42, 'Civil Engineer', 'Active'),
('Guzmán', 'Henry', 'Arthur', 57, 'Professor', 'Active'),
('Shaw', 'Gabriel', 'Michael', 31, 'Statistician', 'Active'),
('Rojas', 'Sofia', 'Joy', 48, 'Oceanographer', 'Active'),
('West', 'Benjamin', 'Alan', 24, 'Meteorologist', 'Active'),
('Acuña', 'Mia', 'Isabelle', 39, NULL, 'Unemployed'),
('Fisher', 'Wyatt', 'Finn', 54, 'Lobbyist', 'Active'),
('Ramírez', 'Lucas', 'Andrew', 26, 'Auditor', 'Active'),
('Kennedy', 'Valeria', 'Paz', 43, 'Interior Designer', 'Active'),
('Ochoa', 'Oscar', 'René', 37, 'Investment Banker', 'Active'),
('Cole', 'Laura', 'Sofía', 59, 'Social Worker', 'Active'),
('Scott', 'Daniel', 'Felipe', 27, 'Librarian', 'Active'),
('López', 'Victoria', 'Skye', 50, 'Speech Pathologist', 'Active'),
('Harris', 'Javier', 'Ignacio', 32, 'Truck Driver', 'Active'),
('Molina', 'Chloe', 'Nicole', 44, 'High School Teacher', 'Active'),
('Perry', 'Marcus', 'Drew', 55, 'Fitness Trainer', 'Active'),
('Rivera', 'Nora', 'Jean', 21, 'Pilot', 'Active'),
('Morgan', 'Alexander', 'Dean', 46, 'Executive Chef', 'Active'),
('Soto', 'Isabella', 'Andrea', 30, 'Veterinarian', 'Active'),
('Barnes', 'Leo', 'Max', 51, 'Barista', 'Active'),
('Vidal', 'Carla', 'Patricia', 23, 'Mechanical Engineer', 'Active'),
('Foster', 'Isaac', 'Alexander', 49, 'Police Officer', 'Active'),
('Wallace', 'Renata', 'Camila', 34, 'Flight Attendant', 'Active'),
('Reyes', 'Henry', 'James', 57, 'Journalist', 'Active'),
('Díaz', 'Marcos', 'Elías', 28, 'Electrician', 'Active'),
('Cooper', 'Hannah', 'Lynn', 45, 'Financial Analyst', 'Active'),
('Acosta', 'Juan', 'Carlos', 33, 'Physiotherapist', 'Active'),
('Richardson', 'Ella', 'Rose', 52, 'Geologist', 'Active'),
('Peralta', 'Pablo', 'Antonio', 25, 'Paramedic', 'Active'),
('Gray', 'Ethan', 'Oliver', 40, 'IT Consultant', 'Active'),
('Mendoza', 'Valeria', 'Paz', 53, 'Marketing Director', 'Active'),
('James', 'Aurora', 'Dawn', 29, 'Museum Curator', 'Active'),
('Alonso', 'Miguel', 'Ángel', 41, 'Chiropractor', 'Active'),
('Price', 'Mia', 'Sofia', 58, 'Dentist', 'Active'),
('Salazar', 'Laura', 'Beatriz', 36, 'Professor', 'Active'),
('Bailey', 'Diego', 'Alejandro', 47, 'Receptionist', 'Active'),
('Torres', 'Javier', 'Ignacio', 22, 'Forensic Scientist', 'Active'),
('Sanders', 'Chloe', 'Nicole', 55, 'Data Scientist', 'Active'),
('Castro', 'Thomas', 'Edward', 37, 'Accountant', 'Active'),
('Bryant', 'Jessica', 'Lynn', 44, 'Aerospace Engineer', 'Active'),
('Duque', 'Robert', 'Alan', 35, 'Chef', 'Active'),
('Powell', 'Emily', 'Sarah', 50, 'Operations Manager', 'Active'),
('Montes', 'John', 'Michael', 26, 'Chef', 'Active'),
('Flores', 'Carlos', 'Alberto', 42, 'Librarian', 'Active'),
('Jenkins', 'Sofía', 'Alejandra', 33, 'HR Manager', 'Active'),
('Ramos', 'Daniel', 'Felipe', 56, 'Biotech Specialist', 'Active'),
('Perry', 'Mia', 'Jade', 28, 'Graphic Designer', 'Active'),
('Vargas', 'Lucas', 'Andrew', 49, 'Electrician', 'Active'),
('Russell', 'Isabella', 'Andrea', 31, 'Teacher', 'Active'),
('Bravo', 'Thomas', 'Edward', 53, 'Physicist', 'Active'),
('Wood', 'Chloe', 'Rose', 24, 'Real Estate Agent', 'Active'),
('Serrano', 'Owen', 'Rhys', 40, 'Firefighter', 'Active'),
('Butler', 'Ryan', 'Patrick', 57, 'Software Developer', 'Active'),
('Ibarra', 'Hannah', 'Lynn', 30, 'Social Worker', 'Active'),
('Hayes', 'Ethan', 'Oliver', 46, 'Nurse', 'Active'),
('Luna', 'Victoria', 'Skye', 39, 'Project Manager', 'Active'),
('Bennett', 'David', 'James', 51, 'Marketing Specialist', 'Active'),
('Cano', 'Avery', 'Noelle', 27, 'Accountant', 'Active'),
('Foster', 'Julian', 'Dean', 43, 'Recruiter', 'Active'),
('Peña', 'Ella', 'Faith', 54, 'Supply Chain Analyst', 'Active'),
('Barnes', 'Alexander', 'Cole', 25, 'Customer Service Manager', 'Active'),
('Del Río', 'Penelope', 'Kate', 48, NULL, 'Unemployed'),
('Cole', 'Samuel', 'Joseph', 34, 'Lawyer', 'Active'),
('Rivas', 'Grace', 'Harper', 55, 'Architect', 'Active'),
('Henderson', 'Elijah', 'Kyle', 29, 'Financial Advisor', 'Active'),
('Kelly', 'Zoey', 'Violet', 42, 'Civil Engineer', 'Active'),
('Pizarro', 'Leo', 'Benjamin', 36, 'Journalist', 'Active'),
('Stone', 'Lily', 'Rose', 50, 'Statistician', 'Active'),
('Silva', 'Henry', 'Arthur', 33, 'Chef', 'Active'),
('Brooks', 'Gabriel', 'Michael', 57, 'Dentist', 'Active'),
('Velez', 'Sofia', 'Joy', 21, 'Urban Planner', 'Active'),
('Wallace', 'Benjamin', 'Alan', 45, 'Meteorologist', 'Active'),
('Zárate', 'Mia', 'Isabelle', 38, 'Pharmacist', 'Active'),
('Peterson', 'Wyatt', 'Finn', 52, 'Content Writer', 'Active'),
('Núñez', 'Lucas', 'Andrew', 26, 'High School Teacher', 'Active'),
('Grant', 'Valeria', 'Paz', 41, 'Travel Agent', 'Active'),
('Rojas', 'Oscar', 'René', 58, 'Mechanic', 'Active'),
('Murray', 'Laura', 'Sofía', 30, 'Biologist', 'Active'),
('Quiroga', 'Daniel', 'Felipe', 53, 'Lobbyist', 'Active'),
('Long', 'Victoria', 'Skye', 24, 'Surgeon', 'Active'),
('Vidal', 'Javier', 'Ignacio', 40, 'Psychologist', 'Active'),
('Harrison', 'Chloe', 'Nicole', 59, 'Economist', 'Active'),
('Tapia', 'Thomas', 'Edward', 35, 'System Administrator', 'Active'),
('Gibson', 'Jessica', 'Lynn', 56, 'Graphic Designer', 'Active'),
('Fuentes', 'Robert', 'Alan', 22, 'Sales Representative', 'Active'),
('Ellis', 'Emily', 'Sarah', 43, 'Data Analyst', 'Active'),
('Guerrero', 'John', 'Michael', 37, 'Operations Director', 'Active'),
('Graham', 'Laura', 'Beatriz', 54, 'HR Coordinator', 'Active'),
('Paredes', 'Mario', 'Gabriel', 29, 'Financial Advisor', 'Active');
SELECT first_Name, last_Name, age, job_Type FROM employees_table WHERE age=35;
SELECT first_Name, last_Name, age, job_Type FROM employees_table WHERE age=51;
SELECT last_Name, age FROM employees_table WHERE first_Name='Luis';
SELECT first_Name AS Name, last_Name AS Surname, age FROM employees_table WHERE age=34;
SELECT * FROM employees_table;
SET SQL_SAFE_UPDATES = 0;
UPDATE employees_Table SET job_Type='Product Owner' WHERE job_Type='Operations Manager';
COMMIT;
SELECT DISTINCT job_Type FROM employees_Table;
SELECT first_Name AS Name FROM employees_Table WHERE job_Type='Product Owner' ;